### ISSUE TITLE
Error for Real-world Validation

### ISSUE THREAD

**Issue by noah123-debug** [hello-maker/PIDiff#1]
Thank you for sharing nice job! But when I run ./scripts/real_world/Inference.ipynb, some errors has occurred.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 16
     14 from tqdm.auto import tqdm
     15 from utils.data import PDBProtein, parse_sdf_file
---> 16 from mol_tree import *
     17 import rdkit
     18 import rdkit.Chem as Chem

ModuleNotFoundError: No module named 'mol_tree'

This looks like missing the mol_tree file. Thank you very much!

**Comment by hello-maker** [comment]
Hello!
You may already be aware of this, but since mol_tree is not directly utilized in PIDiff, I recommend commenting it out before running the code. 
Best regards.
